# Generated by Django 4.0.1 on 2022-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
